rootLogger.level = ERROR
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n

# Silence specific noisy loggers
logger.ivy.name = org.apache.ivy
logger.ivy.level = ERROR
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR
logger.spark.name = org.apache.spark
logger.spark.level = ERROR